apiVersion: v1
data:
  htpasswd: dXNlcjExOiQyeSQwNSRKOXFMVlAudENTTXpQTU8yMlNZOWllWThuQVZpMmxvZ1ZaTFVFUjdVbUpHcndOcHd3ZXF6Ngp1c2VyMTI6JDJ5JDA1JGp3L2xnYTNnTG5iZVAwRy9MV01MdnVDOXVBbEVlV1Jkby9ML0Q1c0JkYTVsTk9sN0IzU2ptCnVzZXIxMzokMnkkMDUkeFFiZ3JqQ2dpQ3FiUnhtL1FadUFBT1RBcWp2WWdPYmpjNjRERTBRZFdILlZIWWsvTGVnSTYKdXNlcjE0OiQyeSQwNSRwQU1yZEtmUWRLVnA1S05UWE9qVUpPN0pCdTBodG5qTERESzVvYXBzdjRKejcudnJDdWZYZQp1c2VyMTU6JDJ5JDA1JC9WYVFzcUgwSTUzQzdackdEOUU3a08zbWI2YnpZTW5CUEtoWkVkZURNT213T013dm5xcHhHCg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"app2-secret","namespace":"openshift-config","creationTimestamp":null},"data":{"htpasswd":"dXNlcjExOiQyeSQwNSRKOXFMVlAudENTTXpQTU8yMlNZOWllWThuQVZpMmxvZ1ZaTFVFUjdVbUpHcndOcHd3ZXF6Ngp1c2VyMTI6JDJ5JDA1JGp3L2xnYTNnTG5iZVAwRy9MV01MdnVDOXVBbEVlV1Jkby9ML0Q1c0JkYTVsTk9sN0IzU2ptCnVzZXIxMzokMnkkMDUkeFFiZ3JqQ2dpQ3FiUnhtL1FadUFBT1RBcWp2WWdPYmpjNjRERTBRZFdILlZIWWsvTGVnSTYKdXNlcjE0OiQyeSQwNSRwQU1yZEtmUWRLVnA1S05UWE9qVUpPN0pCdTBodG5qTERESzVvYXBzdjRKejcudnJDdWZYZQp1c2VyMTU6JDJ5JDA1JC9WYVFzcUgwSTUzQzdackdEOUU3a08zbWI2YnpZTW5CUEtoWkVkZURNT213T013dm5xcHhHCg=="}}
  creationTimestamp: null
  name: app2-secret
  namespace: openshift-config
