apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 57bea27a-7d18-4b21-aba8-297e8f830d2d

spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: uid=admin,cn=users,cn=accounts,dc=ocp4,dc=example,dc=com
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldap://idm.ocp4.example.com/cn=users,cn=accounts,dc=ocp4,dc=example,dc=com?uid
    mappingMethod: claim
    name: Red Hat Identity Management
    type: LDAP

  - name: devops-htpasswd-provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: devops-secret 

  - name: app-htpasswd-provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: app-secret 
